#

SELECT A.school_code,
       C.school_name,
       A.target_code,
       B.target_name,
       A.target_val,
       A.fixed_value,
       A.data_year,
       RANK() OVER ( PARTITION BY A.target_code ORDER BY (target_val + 0) DESC ) AS target_rank,
       NULL                                                                      AS target_score
FROM `temporary_rank_tbl_school_target_info` A,
     rank_tbl_module_info_no_edition         B,
     rank_tbl_school_info                    C
WHERE A.school_code = C.school_code
  AND A.target_code = B.target_code
  AND A.data_year = B.default_year
  AND A.school_code IN ( SELECT school_code FROM rank_tbl_school_info WHERE is_211 = '1' )
  AND A.target_code != 'cate0508022'
  AND A.target_code IN ( SELECT target_code
                         FROM rank_tbl_module_info_no_edition
                         WHERE target_name IN ('研本比',
                                               '本专比',
                                               '顶尖学科精度（A+占比）',
                                               '顶尖学科精度（软科前2%占比）',
                                               '一流学科精度（A类占比）',
                                               '一流学科精度（软科前10%占比）',
                                               '优势学科精度（上榜占比）',
                                               '优势学科精度（软科前50%占比）',
                                               '学校收入（生均）',
                                               '自主收入比例（其他渠道收入占比）',
                                               '社会捐赠收入（生均）',
                                               '师生比',
                                               '教师学历结构（博士学位教师占比）',
                                               '教师职称结构（高级职称教师占比）',
                                               '模范先进教师（生均折合数）',
                                               '模范先进学生（生均折合数）',
                                               '思政课程名师（生均折合数）',
                                               '思政教育队伍（生均折合数）',
                                               '思政教育基地（生均折合数）',
                                               '直接生师比',
                                               '国家级与认证专业（生均）',
                                               '本科课程（生均）',
                                               '国家一流本科课程（生均）',
                                               '规划与马工程教材（生均）',
                                               '国家教学名师（生均）',
                                               '教授授课率',
                                               '授课教授比例',
                                               '国家教学基地（生均折合数）',
                                               '国家教学成果奖（师均折合数）',
                                               '研究生教育成果奖（师均折合数）',
                                               '科创竞赛奖（生均折合数）',
                                               '本科毕业生就业率',
                                               '本科毕业生深造率',
                                               '造就学术人才（生均）',
                                               '造就医学人才（生均）',
                                               '造就财经人才（生均）',
                                               '科研经费（师均）',
                                               '自科面上青年项目（师均）',
                                               '社科一般青年项目（师均）',
                                               '国家科研项目（师均）',
                                               '国际期刊论文（师均）',
                                               '中文期刊论文（师均）',
                                               '科研平台（师均折合数）',
                                               '企业科研经费（师均）',
                                               '发明专利申请（师均）',
                                               '发明专利授权（师均）',
                                               'PCT国际专利申请（师均）',
                                               '专利获奖（师均折合数）',
                                               '技术转让收入（师均）',
                                               '资深学术权威（师均）',
                                               '中年领军专家（师均）',
                                               '青年拔尖英才（师均）',
                                               '文科学术骨干（师均）',
                                               '国际知名学者（师均）',
                                               '学术人才（师均）',
                                               '自科重大项目（师均额度）',
                                               '社科重大项目（师均折合数）',
                                               '国家重大项目（师均折合数）',
                                               '国家重大奖励（师均折合数）',
                                               '教育部科学技术奖（师均折合数）',
                                               '教育部人文社科奖（师均折合数）',
                                               '教育部奖励（师均折合数）',
                                               '留学生比例',
                                               '国际教师比例',
                                               '国际合作论文比例'
                             ) );